channels:
- conda-forge
dependencies:
- python=3.12.1
- pip<=25.0
- pip:
  - mlflow==2.20.1
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - pandas==2.2.2
  - psutil==6.1.1
  - scikit-learn==1.6.1
  - scipy==1.14.0
name: mlflow-env
